name: i-Invested.co.uk
favicon: null
layout_spectrum: 0.60132
typography_spectrum: 0.82226
title: i-Invested
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15c1ff'
    - '#86d6f1'
    - '#45c2e5'
    - '#b9e5f3'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
